In [ ]:
import pandas as pd

df=pd.read_csv("income.csv")
df.head()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week,income_level
0,39,77516,13,2174,0,40,0
1,50,83311,13,0,0,13,0
2,38,215646,9,0,0,40,0
3,53,234721,7,0,0,40,0
4,28,338409,13,0,0,40,0

In [ ]:
df.isnull().sum()

age               0
fnlwgt            0
education_num     0
capital_gain      0
capital_loss      0
hours_per_week    0
income_level      0
dtype: int64

In [ ]:
X=df.drop("income_level", axis=1)
Y=df["income_level"]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.ensemble import AdaBoostClassifier

ada_10=AdaBoostClassifier(n_estimators=10, random_state=42)
ada_10.fit(X_train, Y_train)

Y_pred_10=ada_10.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix

accuracy=accuracy_score(Y_test, Y_pred_10)
cm=confusion_matrix(Y_test, Y_pred_10)

print("Accuracy for 10 estimators: ", accuracy)
print("Confusion Matrix for 10 estimators: ", cm)

Accuracy for 10 estimators:  0.8182004299314157
Confusion Matrix for 10 estimators:  [[6782  632]
 [1144 1211]]

In [ ]:
best_score=0
best_n_estimators=0



for est in [10, 20, 50, 100, 150, 160, 180, 200]:
  model=AdaBoostClassifier(n_estimators=est, random_state=42)
  model.fit(X_train, Y_train)
  Y_pred=model.predict(X_test)
  accuracy=accuracy_score(Y_test, Y_pred)

  if (accuracy > best_score):
    best_score=accuracy
    best_n_estimators=est


print("Best Accuracy for ", best_n_estimators," is found to be : ", best_score)

model=AdaBoostClassifier(n_estimators=best_n_estimators, random_state=42)
model.fit(X_train, Y_train)
Y_pred=model.predict(X_test)
cm2=confusion_matrix(Y_test, Y_pred)

print("Confusion Matrix for  ", best_n_estimators," estimators: ", cm2)

Best Accuracy for  160  is found to be :  0.8332480294810114
Confusion Matrix for   160  estimators:  [[7028  386]
 [1243 1112]]