In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_csv("heart.csv")

df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [34]:
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA

In [35]:
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score

In [36]:
le=LabelEncoder()

for col in df.columns:
  if df[col].dtype=='object':
    df[col]=le.fit_transform(df[col])

In [37]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,1,140,289,0,1,172,0,0.0,2,0
1,49,0,2,160,180,0,1,156,0,1.0,1,1
2,37,1,1,130,283,0,2,98,0,0.0,2,0
3,48,0,0,138,214,0,1,108,1,1.5,1,1
4,54,1,2,150,195,0,1,122,0,0.0,2,0

In [38]:
X=df.drop('HeartDisease', axis=1)
Y=df['HeartDisease']

X_train, X_test, Y_train, Y_test= train_test_split(X, Y, test_size=0.2)

scaler=StandardScaler()

X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [39]:
lr=LogisticRegression()
lr.fit(X_train, Y_train)

Y_pred=lr.predict(X_test)
print("LR Accuracy: ", accuracy_score(Y_test, Y_pred))

LR Accuracy:  0.8967391304347826

In [40]:
svm=SVC()
svm.fit(X_train, Y_train)

Y_pred=svm.predict(X_test)
print("SVM Accuracy: ",accuracy_score(Y_test, Y_pred))

SVM Accuracy:  0.8695652173913043

In [41]:
rf=RandomForestClassifier()
rf.fit(X_train, Y_train)

Y_pred=rf.predict(X_test)
print("RF Accuracy: ", accuracy_score(Y_test, Y_pred))

RF Accuracy:  0.8858695652173914

In [42]:
pca=PCA(n_components=5)

In [43]:
X_train_pca=pca.fit_transform(X_train)
X_test_pca=pca.transform(X_test)

In [44]:
lr.fit(X_train_pca, Y_train)

Y_pred=lr.predict(X_test_pca)
print("LR Accuracy after PCA: ", accuracy_score(Y_test, Y_pred))

LR Accuracy after PCA:  0.8913043478260869

In [45]:
svm.fit(X_train_pca, Y_train)

Y_pred=svm.predict(X_test_pca)
print("SVM Accuracy after PCA: ", accuracy_score(Y_test, Y_pred))

SVM Accuracy after PCA:  0.8695652173913043

In [46]:
rf.fit(X_train_pca, Y_train)

Y_pred=rf.predict(X_test_pca)
print("RF Accuracy after PCA: ", accuracy_score(Y_test, Y_pred))

RF Accuracy after PCA:  0.8695652173913043